// Generated by https://quicktype.io

export interface TopLevel {
  Message:       string;
  Type:          number;
  MetaData:      MetaData;
  SponsoredData: any[];
  Data:          Datum[];
  RateLimit:     RateLimit;
  HasWarning:    boolean;
}

export interface Datum {
  CoinInfo: CoinInfo;
  RAW?:     Raw;
  DISPLAY?: Display;
}

export interface CoinInfo {
  Id:                 string;
  Name:               string;
  FullName:           string;
  Internal:           string;
  ImageUrl:           string;
  Url:                string;
  Algorithm:          string;
  ProofType:          string;
  Rating:             Rating;
  NetHashesPerSecond: number;
  BlockNumber:        number;
  BlockTime:          number;
  BlockReward:        number;
  AssetLaunchDate:    string;
  MaxSupply:          number;
  Type:               number;
  DocumentType:       DocumentType;
}

export enum DocumentType {
  Webpagecoinp = "Webpagecoinp",
}

export interface Rating {
  Weiss: Weiss;
}

export interface Weiss {
  Rating:                   string;
  TechnologyAdoptionRating: string;
  MarketPerformanceRating:  string;
}

export interface Display {
  MON: { [key: string]: string };
}

export interface Raw {
  MON: Mon;
}

export interface Mon {
  TYPE:                    string;
  MARKET:                  Market;
  FROMSYMBOL:              string;
  TOSYMBOL:                Tosymbol;
  FLAGS:                   string;
  LASTMARKET:              Market;
  MEDIAN:                  number;
  TOPTIERVOLUME24HOUR:     number;
  TOPTIERVOLUME24HOURTO:   number;
  LASTTRADEID:             string;
  PRICE:                   number;
  LASTUPDATE:              number;
  LASTVOLUME:              number;
  LASTVOLUMETO:            number;
  VOLUMEHOUR:              number;
  VOLUMEHOURTO:            number;
  OPENHOUR:                number;
  HIGHHOUR:                number;
  LOWHOUR:                 number;
  VOLUMEDAY:               number;
  VOLUMEDAYTO:             number;
  OPENDAY:                 number;
  HIGHDAY:                 number;
  LOWDAY:                  number;
  VOLUME24HOUR:            number;
  VOLUME24HOURTO:          number;
  OPEN24HOUR:              number;
  HIGH24HOUR:              number;
  LOW24HOUR:               number;
  CHANGE24HOUR:            number;
  CHANGEPCT24HOUR:         number;
  CHANGEDAY:               number;
  CHANGEPCTDAY:            number;
  CHANGEHOUR:              number;
  CHANGEPCTHOUR:           number;
  CONVERSIONTYPE:          Conversiontype;
  CONVERSIONSYMBOL:        Conversionsymbol;
  CONVERSIONLASTUPDATE:    number;
  SUPPLY:                  number;
  MKTCAP:                  number;
  MKTCAPPENALTY:           number;
  CIRCULATINGSUPPLY:       number;
  CIRCULATINGSUPPLYMKTCAP: number;
  TOTALVOLUME24H:          number;
  TOTALVOLUME24HTO:        number;
  TOTALTOPTIERVOLUME24H:   number;
  TOTALTOPTIERVOLUME24HTO: number;
  IMAGEURL:                string;
}

export enum Conversionsymbol {
  Empty = "",
  Eth = "ETH",
}

export enum Conversiontype {
  Direct = "direct",
  Multiply = "multiply",
}

export enum Market {
  Cccagg = "CCCAGG",
}

export enum Tosymbol {
  Mon = "USD",
}

export interface MetaData {
  Count: number;
}

export interface RateLimit {
}
